### ISSUE TITLE
The ath9k wireless NIC model

### ISSUE THREAD

**Issue by fchen22** [xieyaxiongfly/Atheros-CSI-Tool#10]
I have bought two 9380/9390 miniPCIe cards from Taobao, the PCI ID is 0x168c:0x0030 and set them in two PCs, One as AP, one as STA, AP can log the received msg with recv_csi program, but the csi len is always 0, you can refer to below log

Recv 18th msg with rate: 0x8f | payload len: 1540
Timestamp 0
Channel: 2437
Bandwidth: 0
Rate: 143
NR: 3
NC: 3
Tones: 56
Phyerr: 0
RSSI0: 219
RSSI1: 45
RSSI2: 36
RSSI3: 41
Payload Len: 1540
CSI Len: 0

And here is the kernel log about this chip

csi@ubuntuCSI:~/NovelSense$ uname -a
Linux ubuntuCSI 4.1.10-040110-generic #201510030837 SMP Sat Oct 3 12:38:41 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

csi@ubuntuCSI:/NovelSense/recvCSI$ dmesg | grep ath
[ 8.552767] ath: EEPROM regdomain: 0x64
[ 8.552768] ath: EEPROM indicates we should expect a direct regpair map
[ 8.552770] ath: Country alpha2 being used: 00
[ 8.552770] ath: Regpair used: 0x64
[ 8.668764] ath9k 0000:02:00.0 wlan2: renamed from wlan0
csi@ubuntuCSI:/NovelSense/recvCSI$ dmesg | grep AR93
[ 8.667099] ieee80211 phy0: Atheros AR9300 Rev:3 mem=0xffffc90000f80000, irq=16

here is the lspci output

02:00.0 0280: 168c:0030 (rev 01)
Subsystem: 106b:009a
Flags: bus master, fast devsel, latency 0, IRQ 16
Memory at f7000000 (64-bit, non-prefetchable) [size=128K]
Expansion ROM at f7020000 [disabled] [size=64K]
Capabilities: [40] Power Management version 2
Capabilities: [50] MSI: Enable- Count=1/4 Maskable+ 64bit+
Capabilities: [70] Express Endpoint, MSI 00
Capabilities: [100] Advanced Error Reporting
Capabilities: [140] Virtual Channel
Capabilities: [300] Device Serial Number 00-00-00-00-00-00-00-00
Kernel driver in use: ath9k

I am thinking it maybe the wrong card model issue. So can you let me know what model you are using and where can buy it?

thanks

**Comment by EuclidGH** [comment]
Hi,

If your cards are really AR9380 and AR9390 then it should work, because I use also use these models. However, my cards do not support 2.4 GHz bands.

To answer your question, I need more information and please answer the following questions?

Did you perform the CSI-Tool installation as it is reported in the documentation?
Which kind of devices do you use as transmitter and receiver?

If you use a direct connection over hostapd between two devices, you should have the payload less than 1500 bytes. In your case, your payload is 1540 bytes and it destroys the whole CSI data. For more information about the maximal length of the payload, you have to read how the ethernet frame type II is built.

Anyway, you have to follow the documentation and use the same Ubuntu version.

**Comment by fchen22** [comment]
Thanks guy. Finally I got the CSI data. Still do not know the real reason. 
Ubuntu kernel 3.13.0.57 and 4.1.10-040110-generic both work well. Payload 1540 does not matter, either.
Anyway, thanks again
