### ISSUE TITLE
Diff of Kernel/Tool modifications

### ISSUE THREAD

**Issue by brunosoaresds** [xieyaxiongfly/Atheros-CSI-Tool#3]
Hi,

Do you have a diff of all tool modifications on the Kernel? I want to map the tool and after try to modify it to use with a single node (client), like the #2 issue.

Best Regards,

**Comment by xieyaxiongfly** [comment]
Sorry, I didn't have a such a diff. You can generate such a diff by yourself, am I right?

And I am also working on that issue right now. It is very difficult and I cant find a suitable way to bypass the modification at the sender side.

**Comment by BrunoSoares-LABORA** [comment]
@xieyaxiongfly 

Can you explain to me why we need this modifications (and what is this modifications) in the sender side? Why we can't collect the CSI data by all packets in the network? maybe i can help you if i understand the problem.

**Comment by xieyaxiongfly** [comment]
The problem is because of the CSI calculation functionality. Atheros WiFi cards only calculate CSI for HT sounding packets. Therefore, we need to modify the sender to open the sounding flag of every HT packet so that it becomes a sounding packet.

Such a logic is embeded into the firmware of Atheros WiFi cards which I am not able to modify. 

That's the problem I met at this moment.

**Comment by BrunoSoares-LABORA** [comment]
@xieyaxiongfly 

Thanks, now i understand better the problem, it's really difficult to solve it.
I have other ask for you: Can i transform the CSI complex value to RSSI? if yes, how can i do it?
